/**
 * Ordem da história de cada jogo, para listar os Pokémon na ordem em que o
 * jogador os encontra (iniciais → rotas → … → lendários).
 *
 * `areas` são prefixos dos nomes de área da PokeAPI, na ordem em que se chega
 * a eles. `methods` e `conditions` dizem a partir de qual área a forma de
 * encontro fica disponível (a Super Rod só vem na Route 12, o rádio só no
 * pós-jogo…): um encontro vale no ponto mais tardio entre a área e o que ele
 * exige.
 */
export const PROGRESSION = {
  frlg: {
    starters: [1, 4, 7],
    areas: [
      'Pallet Town',
      'Route 1',
      'Viridian City',
      'Route 22',
      'Route 2',
      'Viridian Forest',
      'Route 3',
      'Pokemon Center (Road 3)',
      'Pokemon Center (Road 4)',
      'Mount Moon',
      'Route 4',
      'Cerulean City',
      'Route 24',
      'Route 25',
      'Route 5',
      'Route 6',
      'Vermilion City',
      'S.S. Anne',
      'Route 11',
      'Digletts Cave',
      'Route 9',
      'Route 10',
      'Rock Tunnel',
      'Route 8',
      'Route 7',
      'Kanto Underground Path',
      'Celadon City Prize Corner',
      'Celadon Mansion rooftop',
      'Celadon City',
      'Pokemon Tower',
      'Route 12',
      'Route 13',
      'Route 14',
      'Route 15',
      'Route 16',
      'Route 17',
      'Route 18',
      'Fuchsia City',
      'Safari Zone',
      'Fighting Dojo',
      'Silph Co.',
      'Route 19',
      'Route 20',
      'Seafoam Islands',
      'Cinnabar Island',
      'Pokemon Mansion',
      'Cinnabar Lab',
      'Route 21',
      'Power Plant',
      'Route 23',
      'Victory Road',
      'One Island',
      'Kindle Road',
      'Mount Ember',
      'Treasure Beach',
      'Two Island',
      'Cape Brink',
      'Three Island',
      'Bond Bridge',
      'Berry Forest',
      'Four Island',
      'Icefall Cave',
      'Five Island',
      'Five Isle Meadow',
      'Memorial Pillar',
      'Water Labyrinth',
      'Resort Gorgeous',
      'Lost Cave',
      'Water Path',
      'Ruin Valley',
      'Green Path',
      'Outcast Island',
      'Pattern Bush',
      'Altering Cave',
      'Sevault Canyon',
      'Canyon Entrance',
      'Tanoby Ruins',
      'Trainer Tower',
      'Cerulean Cave',
    ],
    methods: {
      'old-rod': 'Vermilion City',
      'good-rod': 'Fuchsia City',
      'super-rod': 'Route 12',
      // HM03 fica no Safari Zone.
      surf: 'Safari Zone',
      'rock-smash': 'One Island',
      pokeflute: 'Pokemon Tower',
    },
    conditions: {},
  },
  hgss: {
    starters: [152, 155, 158],
    areas: [
      'New Bark Town',
      'Route 29',
      'Cherrygrove City',
      'Route 30',
      'Route 31',
      'Violet City',
      'Sprout Tower',
      'Route 32',
      'Ruins of Alph',
      'Union Cave',
      'Route 33',
      'Azalea Town',
      'Slowpoke Well',
      'Ilex Forest',
      'Route 34',
      'Goldenrod City',
      'Route 35',
      'National Park',
      'Route 36',
      'Route 37',
      'Ecruteak City',
      'Burned Tower',
      // Os cães lendários passam a vagar depois da Burned Tower.
      'Wandert durch Johto',
      'Route 38',
      'Route 39',
      'Olivine City',
      'Route 40',
      'Route 41',
      'Cianwood City',
      'Pokemon Center (Cianwood City)',
      'Route 47',
      'Route 48',
      'Safari Zone',
      'Route 42',
      'Mount Mortar',
      'Route 43',
      'Lake of Rage',
      'Team Rocket HQ',
      'Route 44',
      'Ice Path',
      'Blackthorn City',
      "Dragon's Den",
      'Route 45',
      'Route 46',
      'Dark Cave',
      'Whirl Islands',
      'Bell Tower',
      'Route 27',
      'Tohjo Falls',
      'Route 26',
      'Victory Road 1',
      // Kanto, depois da Liga.
      'S.S. Anne dock',
      'Vermilion City',
      'Route 6',
      'Saffron City',
      'Silph Co.',
      'Route 11',
      'Digletts Cave',
      'Route 5',
      'Cerulean City',
      'Route 24',
      'Route 25',
      'Route 9',
      'Route 10',
      'Rock Tunnel',
      'Power Plant',
      'Route 8',
      'Route 7',
      'Celadon City Prize Corner',
      'Celadon City',
      'Route 16',
      'Route 17',
      'Route 18',
      'Fuchsia City',
      'Route 15',
      'Route 14',
      'Route 13',
      'Route 12',
      'Route 19',
      'Route 20',
      'Seafoam Islands',
      'Cinnabar Island',
      'Route 21',
      'Route 1',
      'Pallet Town',
      'Viridian City',
      'Route 22',
      'Route 2',
      'Viridian Forest',
      'pewter-city-area',
      'Pewter Museum of Science',
      'Route 3',
      'Mount Moon',
      'Route 4',
      'Unknown Area',
      'Route 28',
      'Mount Silver',
      'Cerulean Cave',
      'Embedded Tower',
    ],
    methods: {
      'old-rod': 'Route 32',
      headbutt: 'Ilex Forest',
      'squirt-bottle': 'Goldenrod City',
      'rock-smash': 'Route 36',
      surf: 'Ecruteak City',
      'good-rod': 'Olivine City',
      'super-rod': 'Route 12',
    },
    conditions: {
      'bug-contest': 'National Park',
      'safari-blocks': 'Safari Zone',
      // Rádio (Hoenn/Sinnoh Sound) e swarms só depois da Pokédex Nacional.
      'radio-hoenn': 'S.S. Anne dock',
      'radio-sinnoh': 'S.S. Anne dock',
      swarm: 'S.S. Anne dock',
    },
  },
};
