/**
 * Ordem da história de cada jogo, para listar os Pokémon na ordem em que o
 * jogador os encontra (iniciais → rotas → … → lendários).
 *
 * `areas` são prefixos dos nomes de área da PokeAPI, na ordem em que se chega
 * a eles. `methods` e `conditions` dizem a partir de qual área a forma de
 * encontro fica disponível (a Super Rod só vem na Route 12, o rádio só no
 * pós-jogo…): um encontro vale no ponto mais tardio entre a área e o que ele
 * exige. `notBefore` segura Pokémon cujo local engana (o presente vem numa
 * cidade do começo, mas só depois da Liga).
 */
export const PROGRESSION = {
  frlg: {
    starters: [1, 4, 7],
    areas: [
      'Pallet Town',
      'Route 1',
      'Viridian City',
      'Route 22',
      'Route 2',
      'Viridian Forest',
      'Route 3',
      'Pokemon Center (Road 3)',
      'Pokemon Center (Road 4)',
      'Mount Moon',
      'Route 4',
      'Cerulean City',
      'Route 24',
      'Route 25',
      'Route 5',
      'Route 6',
      'Vermilion City',
      'S.S. Anne',
      'Route 11',
      'Digletts Cave',
      'Route 9',
      'Route 10',
      'Rock Tunnel',
      'Route 8',
      'Route 7',
      'Kanto Underground Path',
      'Celadon City Prize Corner',
      'Celadon Mansion rooftop',
      'Celadon City',
      'Pokemon Tower',
      'Route 12',
      'Route 13',
      'Route 14',
      'Route 15',
      'Route 16',
      'Route 17',
      'Route 18',
      'Fuchsia City',
      'Safari Zone',
      'Fighting Dojo',
      'Silph Co.',
      'Route 19',
      'Route 20',
      'Seafoam Islands',
      'Cinnabar Island',
      'Pokemon Mansion',
      'Cinnabar Lab',
      'Route 21',
      'Power Plant',
      'Route 23',
      'Victory Road',
      'One Island',
      'Kindle Road',
      'Mount Ember',
      'Treasure Beach',
      'Two Island',
      'Cape Brink',
      'Three Island',
      'Bond Bridge',
      'Berry Forest',
      'Four Island',
      'Icefall Cave',
      'Five Island',
      'Five Isle Meadow',
      'Memorial Pillar',
      'Water Labyrinth',
      'Resort Gorgeous',
      'Lost Cave',
      'Water Path',
      'Ruin Valley',
      'Green Path',
      'Outcast Island',
      'Pattern Bush',
      'Altering Cave',
      'Sevault Canyon',
      'Canyon Entrance',
      'Tanoby Ruins',
      'Trainer Tower',
      'Cerulean Cave',
    ],
    methods: {
      'old-rod': 'Vermilion City',
      'good-rod': 'Fuchsia City',
      'super-rod': 'Route 12',
      // HM03 fica no Safari Zone.
      surf: 'Safari Zone',
      'rock-smash': 'One Island',
      pokeflute: 'Pokemon Tower',
    },
    conditions: {},
  },
  hgss: {
    starters: [152, 155, 158],
    areas: [
      'New Bark Town',
      'Route 29',
      'Cherrygrove City',
      'Route 30',
      'Route 31',
      'Violet City',
      'Sprout Tower',
      'Route 32',
      'Ruins of Alph',
      'Union Cave',
      'Route 33',
      'Azalea Town',
      'Slowpoke Well',
      'Ilex Forest',
      'Route 34',
      'Goldenrod City',
      'Route 35',
      'National Park',
      'Route 36',
      'Route 37',
      'Ecruteak City',
      'Burned Tower',
      // Os cães lendários passam a vagar depois da Burned Tower.
      'Wandert durch Johto',
      'Route 38',
      'Route 39',
      'Olivine City',
      'Route 40',
      'Route 41',
      'Cianwood City',
      'Pokemon Center (Cianwood City)',
      'Route 47',
      'Route 48',
      'Safari Zone',
      'Route 42',
      'Mount Mortar',
      'Route 43',
      'Lake of Rage',
      'Team Rocket HQ',
      'Route 44',
      'Ice Path',
      'Blackthorn City',
      "Dragon's Den",
      'Route 45',
      'Route 46',
      'Dark Cave',
      'Whirl Islands',
      'Bell Tower',
      'Route 27',
      'Tohjo Falls',
      'Route 26',
      'Victory Road 1',
      // Kanto, depois da Liga.
      'S.S. Anne dock',
      'Vermilion City',
      'Route 6',
      'Saffron City',
      'Silph Co.',
      'Route 11',
      'Digletts Cave',
      'Route 5',
      'Cerulean City',
      'Route 24',
      'Route 25',
      'Route 9',
      'Route 10',
      'Rock Tunnel',
      'Power Plant',
      'Route 8',
      'Route 7',
      'Celadon City Prize Corner',
      'Celadon City',
      'Route 16',
      'Route 17',
      'Route 18',
      'Fuchsia City',
      'Route 15',
      'Route 14',
      'Route 13',
      'Route 12',
      'Route 19',
      'Route 20',
      'Seafoam Islands',
      'Cinnabar Island',
      'Route 21',
      'Route 1',
      'Pallet Town',
      'Viridian City',
      'Route 22',
      'Route 2',
      'Viridian Forest',
      'Pewter City',
      'Pewter Museum of Science',
      'Route 3',
      'Mount Moon',
      'Route 4',
      'Unknown Area',
      'Route 28',
      'Mount Silver',
      'Cerulean Cave',
      'Embedded Tower',
    ],
    methods: {
      'old-rod': 'Route 32',
      headbutt: 'Ilex Forest',
      'squirt-bottle': 'Goldenrod City',
      'rock-smash': 'Route 36',
      surf: 'Ecruteak City',
      'good-rod': 'Olivine City',
      'super-rod': 'Route 12',
    },
    conditions: {
      'bug-contest': 'National Park',
      'safari-blocks': 'Safari Zone',
      // Rádio (Hoenn/Sinnoh Sound) e swarms só depois da Pokédex Nacional.
      'radio-hoenn': 'S.S. Anne dock',
      'radio-sinnoh': 'S.S. Anne dock',
      swarm: 'S.S. Anne dock',
    },
  },
  rse: {
    starters: [252, 255, 258],
    // Ordem de Emerald; Ruby/Sapphire seguem o mesmo caminho.
    areas: [
      'Littleroot Town',
      'Route 101',
      'Oldale Town',
      'Route 103',
      'Route 102',
      'Petalburg City',
      'Route 104',
      'Petalburg Woods',
      'Rustboro City',
      'Route 116',
      'Rusturf Tunnel',
      'Dewford Town',
      'Granite Cave',
      'Slateport City',
      'Route 110',
      'Mauville City',
      'Route 117',
      'Verdanturf Town',
      'Route 111',
      'Route 112',
      'Fiery Path',
      'Route 113',
      'Fallarbor Town',
      'Route 114',
      'Meteor Falls',
      'Route 115',
      'Jagged Pass',
      'Magma Hideout',
      'Team Magma Hideout',
      'Lavaridge Town',
      // Marcador: HM03 Surf vem depois da 5ª insígnia (Norman).
      '— Surf (5ª insígnia)',
      'Route 105',
      'Route 106',
      'Route 107',
      'Route 108',
      'Route 109',
      'Abandoned Ship',
      'New Mauville',
      'Route 118',
      'Route 119',
      'Weather Institute',
      'Fortree City',
      'Route 120',
      'Route 121',
      'Safari Zone',
      'Route 122',
      'Mount Pyre',
      'Route 123',
      'Lilycove City',
      'Team Aqua Hideout',
      'Route 124',
      'Mossdeep City',
      // Marcador: HM08 Dive vem depois da 7ª insígnia (Tate & Liza).
      '— Dive (7ª insígnia)',
      'Route 125',
      'Shoal Cave',
      'Route 126',
      'Route 127',
      'Route 128',
      'Seafloor Cavern',
      'Sootopolis City',
      'Cave of Origin',
      'Route 129',
      'Route 130',
      'Route 131',
      'Pacifidlog Town',
      'Route 132',
      'Route 133',
      'Route 134',
      'Sky Pillar',
      'Ever Grande City',
      'Victory Road',
      // Pós-jogo.
      "Mossdeep City (Steven's house)",
      'Safari Zone (expansion',
      'Desert Ruins',
      'Island Cave',
      'Ancient Tomb',
      'Mirage Tower',
      'Mirage Island',
      'Desert Underpass',
      'Altering Cave',
      'Artisan Cave',
      'Hoenn Battle Frontier',
      'Roaming Hoenn',
      'Marine Cave',
      'Terra Cave',
      'Sky Pillar Apex',
    ],
    methods: {
      'old-rod': 'Dewford Town',
      'rock-smash': 'Mauville City',
      surf: '— Surf (5ª insígnia)',
      'good-rod': 'Route 118',
      'feebas-tile-fishing': 'Route 119',
      'devon-scope': 'Route 120',
      'super-rod': 'Mossdeep City',
      seaweed: '— Dive (7ª insígnia)',
    },
    conditions: {},
    notBefore: {
      // Iniciais de Johto: presente do Birch em Littleroot, depois da Liga (Emerald).
      152: "Mossdeep City (Steven's house)",
      155: "Mossdeep City (Steven's house)",
      158: "Mossdeep City (Steven's house)",
    },
  },
};
